### ISSUE TITLE
_tkinter.TclError: bitmap "./assets/logo.ico" not defined

### ISSUE THREAD

**Issue by pab-h** [pab-h/LogicLab#1]
Ao inicializar o projeto pelo Poetry, o seguinte erro é lançado:
```
poetry run start

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pablo/Documents/github/logiclab/scripts.py", line 11, in start
    main()
  File "/home/pablo/Documents/github/logiclab/main.py", line 4, in main
    with App() as app:
         ^^^^^
  File "/home/pablo/Documents/github/logiclab/logiclab/app.py", line 12, in __init__
    self.iconbitmap("./assets/logo.ico")
  File "/home/pablo/.pyenv/versions/3.12.0/lib/python3.12/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "./assets/logo.ico" not defined
```

**Comment by pab-h** [comment]
Aparentemente, a imagem não está formatada corretamente. [Veja  fonte](https://www.linux.org/threads/i-do-not-knows-how-to-noted-a-file-path-in-tkinter-python.42002/)

> If you're still getting the error message _tkinter.TclError: bitmap "picture.ico" not defined, it might be because the file is not in the correct format or cannot be opened. Make sure that the file exists at the specified path and is in the .ico format.

**Comment by pab-h** [comment]
Tentei converter a imagem ./assets/logo.ico para .png e depois para .ico. Mas, não funcionou. 

```
poetry run start

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pablo/Documents/github/logiclab/scripts.py", line 11, in start
    main()
  File "/home/pablo/Documents/github/logiclab/main.py", line 4, in main
    with App() as app:
         ^^^^^
  File "/home/pablo/Documents/github/logiclab/logiclab/app.py", line 12, in __init__
    self.iconbitmap("assets/logo.ico")
  File "/home/pablo/.pyenv/versions/3.12.0/lib/python3.12/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "assets/logo.ico" not defined
```

**Comment by pab-h** [comment]
Tentei converter a imagem ./assets/logo.ico para .bmp. Mas, não funcionou.

```
poetry run start

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pablo/Documents/github/logiclab/scripts.py", line 11, in start
    main()
  File "/home/pablo/Documents/github/logiclab/main.py", line 4, in main
    with App() as app:
         ^^^^^
  File "/home/pablo/Documents/github/logiclab/logiclab/app.py", line 12, in __init__
    self.iconbitmap("assets/logo.bmp")
  File "/home/pablo/.pyenv/versions/3.12.0/lib/python3.12/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "assets/logo.bmp" not defined
```

**Comment by pab-h** [comment]
Achei a solução em [How to replace the icon in a Tkinter app?](https://stackoverflow.com/questions/33137829/how-to-replace-the-icon-in-a-tkinter-app):

```python
class App(tk.Tk):
    def __init__(self) -> None:
        super().__init__()

        self.title("LogicLab")
        self.geometry("1280x720")
        self.resizable(False, False)
        self.iconphoto(
            True,
            tk.PhotoImage(file = "assets/logo.png")
        )
        
        self.helloFrame = HelloFrame(self)
```
